ReactAdminBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            default: '0'
    lifecycleCallbacks: {  }
